#FOB Uptime Monitor \u2013 Email Settings
#Sat Jun 13 17:35:14 BST 2026
fromEmail=femi.adeyemi@fob.ng
smtpHost=smtp.office365.com
smtpPass=London1@
smtpPort=587
smtpUser=femi.adeyemi@fob.ng
toEmail=femi.adeyemi@fob.ng
