server.address=192.168.2.41
server.port=8080
spring.datasource.url=jdbc:sqlite:data.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Mail Configuration Defaults
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sslactions@gmail.com
spring.mail.password=pbkj mvaf khnn sxjk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Custom Application Property for Corporate Notifications
app.notification.corporate-email=femi.adeyemi@fob.ng
